language: python

python:
 - "2.7"
 - "3.3"

env:
  - PLATFORM=u1604
  - PLATFORM=c7

sudo: required

services:
 - docker

before_install: pip install flake8

script:
 - flake8 -v .
 - docker build -t ome-files-py -f docker/${PLATFORM}/Dockerfile .
