language: python

python:
 - "2.7"
 - "3.6"

env:
 - PLATFORM=c7
 - PLATFORM=u1604

sudo: required

services:
 - docker

before_install: pip install flake8

before_script: flake8 -v .

script:
 - echo docker build -t ome-files-py -f Dockerfile.${PLATFORM} .
 - echo docker run --name omefilespy -dt ome-files-py
 - echo DEBUG=true ./.travis/run_checks
 - echo docker stop omefilespy
 - echo docker rm omefilespy
